[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google/generative-ai"]

[[redirects]]
  from = "/api/chat"
  to   = "/.netlify/functions/chat"
  status = 200
  force = true

[[redirects]]
  from = "/api/users"
  to   = "/.netlify/functions/users"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin-auth"
  to   = "/.netlify/functions/admin-auth"
  status = 200
  force = true
